name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: build and upload to s3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: install node modules
        run: npm install

      - name: build
        run: CI=false npm run build

      - name: upload build directory to s3
        run: aws s3 cp build s3://${{ secrets.AWS_S3_BUCKET }} --recursive --acl public-read

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}} --paths "/*"